app/settings/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.core import StringField
from flask_babel import _, lazy_gettext as _l
from wtforms.fields.simple import SubmitField
from wtforms.validators import DataRequired, Email, ValidationError
from app.main.models.partner import Partner


class InviteForm(FlaskForm):
    email = StringField(_l('Email Address'),
                        validators=[DataRequired(), Email()])
    submit = SubmitField(_l('Invite'))

    def validate_email(self, email):
        partner = Partner.query.filter_by(email=email.data).first()
        if partner is not None:
            raise ValidationError(
                _('You can not have two users with the same email address!.'))


class NewGroup(FlaskForm):
    pass


class NewUserForm(FlaskForm):
    name = StringField(_l('Name'),
                       validators=[DataRequired()])
    email = StringField(_l('Email Address'),
                        validators=[DataRequired(), Email()])

app/settings/__init__.py
from flask import Blueprint

bp = Blueprint('settings', __name__)

from app.settings import routes
    

app/settings/routes.py
import uuid
import requests
from flask.json import jsonify
from itsdangerous import json
from sqlalchemy import log
from app import db, api_base
from app.auth.email import send_invite_email
from app.decorators import active_user_required, can_create_access_required, can_write_access_required, module_access_required, model_access_required
from app.helper_functions import set_default_user_groups
from app.main.models.country import Country
from app.main.models.module import Model, Module
from app.main.models.partner import Partner
from app.settings import bp
from flask_login import login_required, current_user
from flask import current_app, render_template, redirect, url_for, request, session, flash
from app.settings.forms import InviteForm, NewGroup, NewUserForm
from flask_babel import _, lazy_gettext as _l
from app.auth.models.user import USERTYPES, Access, Permission, UserType, Users, Group, FILTERS

selected_groups = {}

def removekey(d, key):
    r = dict(d)
    del r[key]
    return r


@bp.route("/get_models", methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
def get_models():
    if request.method == "POST":
        models = Model.to_collection_dict(Model.query.order_by('name'))
        return jsonify(models)


@bp.route('/', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
def settings():
    form = InviteForm()
    pending_invitations = Users.query.filter_by(is_active=False).all()
    return render_template('settings/settings.html', title=_('General Settings | Olam ERP'), form=form, pending_invitations=pending_invitations)


@bp.route('/invite', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
def invite():
    form = InviteForm()
    user = Users.query.filter_by(id=current_user.get_id()).first()
    invited_by = Partner.query.filter_by(id=user.partner_id).first()
    if form.validate_on_submit():
        partner = Partner(email=form.email.data)
        partner.generate_slug()
        db.session.add(partner)
        db.session.commit()
        user = Users(partner_id=partner.id)
        user.generate_slug()
        db.session.add(user)
        db.session.commit()
        send_invite_email(partner.id, invited_by.id)
        return jsonify({'response': "success"})
    if form.errors:
        print(form.errors)
        return jsonify({'response': form.errors})


@bp.route('/groups', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
def manage_groups():
    groups = Group.query.filter_by(
        is_active=True).order_by(Group.module_id).all()
    return render_template("settings/groups.html", title=_('Groups | Olam ERP'), groups=groups)


@bp.route('/new_group', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
@can_create_access_required(2)
def new_group():
    form = NewGroup()
    group = None
    models = Model.query.order_by('name').all()
    permissions = Permission

    if form.validate_on_submit():
        exists = Group.query.filter_by(
            name=request.form['group_name']).filter_by(module_id=request.form['select_app']).filter_by(is_active=True).first()
        if exists:
            flash(
                _('A group with this details exists.'))
            return jsonify({"response": "group name exists!"})
        else:
            group = Group(id=uuid.uuid4(
            ), name=request.form['group_name'], module_id=request.form['select_app'], permisssion=request.form['select_permission'])
            group.generate_slug()
            db.session.add(group)
            db.session.commit()
            flash(
                _('Your group has been created successfully.'))
            return jsonify({"response": "success", "slug": group.slug})
    return render_template("settings/new_group.html", title=_('New Group | Olam ERP'), group=group, form=form, models=models, permissions=permissions)


@bp.route('/new_group/<slug>', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
def newgroup(slug):
    form = NewGroup()
    group = Group.query.filter_by(slug=slug).first()
    group_members = Users.query.join(Users.groups).filter_by(slug=slug)
    access_rights = Access.query.join(Access.groups).filter_by(slug=slug)
    models = Model.query.order_by('name').all()
    if form.validate_on_submit():
        exists = Group.query.filter_by(
            name=request.form['group_name']).filter_by(is_active=True).filter_by(module_id=request.form['select_app']).filter(Group.id != group.id).first()
        if exists:
            flash(
                _('A group with this details exists.'))
            return jsonify({"response": "group name exists!"})
        else:
            group.name = request.form['group_name']
            group.module_id = request.form['select_app']
            group.permission = request.form['select_permission']
            db.session.commit()
            flash(
                _('This group has been saved successfully.'))
            return jsonify({"response": "success", "slug": group.slug})
    return render_template("settings/new_group.html", group=group, title=_('New Group | Olam ERP'), group_members=group_members, slug=slug, form=form, models=models, access_rights=access_rights)


@bp.route("/settings/update/<slug>", methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
@can_write_access_required(2)
def update_group(slug):
    form = NewGroup()
    group = Group.query.filter_by(slug=slug).first()
    if form.validate_on_submit():
        exists = Group.query.filter_by(
            name=request.form['group_name']).filter_by(module_id=request.form['select_app']).filter_by(is_active=True).filter(Group.id != group.id).first()
        if exists:
            flash(
                _('A group with this details exists.'))
            return jsonify({"response": "group name exists!", "slug": slug})
        else:
            group.name = request.form['group_name']
            group.module_id = request.form['select_app']
            db.session.commit()
            return jsonify({"response": "success"})
    return redirect(url_for('settings.group', slug=slug))


@bp.route('/group/<slug>', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
def group(slug):
    group = Group.query.filter_by(slug=slug).first()
    group_members = Users.query.join(Users.groups).filter_by(slug=slug)
    access_rights = Access.query.join(Access.groups).filter_by(slug=slug)
    models = Model.query.order_by('name').all()
    if not group:
        return redirect(url_for('settings.new_group'))
    return render_template("settings/group.html", group=group, title=_(str(group.name) + ' | Olam ERP'), group_members=group_members, slug=group.slug, access_rights=access_rights, models=models, page="group_members")


@bp.route('/select_users', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
@can_write_access_required(1)
def select_users():
    if request.method == "POST":
        if "slug" in request.form:
            group = Group.query.filter_by(slug=request.form['slug']).first()
        else:
            group = Group(id=uuid.uuid4())
            group.generate_slug()
            db.session.add(group)
            db.session.commit()
        session['selected_users'] = request.form.getlist(
            'selected_users[]')
        for select_user in session['selected_users']:
            user = Users.query.filter_by(id=int(select_user)).first()
            group.users.append(user)
            db.session.commit()
    return jsonify({"response": "success", "slug": group.slug})


@bp.route('/discard/<slug>', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
def discard_group(slug):
    group = Group.query.filter_by(slug=slug).first()
    db.session.delete(group)
    db.session.commit()
    return redirect(url_for('settings.manage_groups'))


@bp.route('/delete-group', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
def delete_group():
    if request.method == "POST":
        selected = request.form.getlist(
            'selected_groups[]')
        for group in selected:
            group = Group.query.filter_by(id=group).first()
            group.is_active = False
            db.session.commit()
        return jsonify({"response": "success"})


@bp.route('/remove_user', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
def remove_user():
    if request.method == "POST":
        group = Group.query.filter_by(slug=request.form['slug']).first()
        user = Users.query.filter_by(id=request.form['user_id']).first()
        group.users.remove(user)
        db.session.commit()
        return jsonify({'response': 'success'})


@bp.route('/edit_group/<slug>', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
@can_write_access_required(2)
def edit_group(slug):
    edit = True
    form = NewGroup()
    group = Group.query.filter_by(slug=slug).first()
    group_members = Users.query.join(Users.groups).filter_by(slug=slug)
    access_rights = Access.query.join(Access.groups).filter_by(slug=slug)
    models = Model.query.order_by('name').all()
    permissions = Permission
    return render_template("settings/edit_group.html", group=group, title=_("Edit " + str(group.name) + " | Olam ERP"), form=form, group_members=group_members, slug=group.slug, edit=edit, access_rights=access_rights, models=models, permissions=permissions)


@bp.route('/access-right', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(1)
@can_write_access_required(4)
def new_access_right():
    if request.method == "POST":
        if "access" in request.form:
            model_name = None

app/templates/settings/groups_blockhead.html
<style>
    .nk-block-des {
        margin-bottom: 0.5rem;
    }

    .selected-groups {
        color: #0c5460;
        background-color: #d1ecf1;
        border-color: #bee5eb;
        display: none;
    }

    .actions {
        color: #0c5460;
    }

    .li-actions {
        display: none;
    }
</style>
<div class="nk-block-head nk-block-head-sm">
    <div class="nk-block-between">
        {% if title == "Groups | Olam ERP" %}
        <div class="nk-block-head-content">
            <h3 class="nk-block-title page-title"><a href="{{url_for('settings.settings')}}">
                    Settings
                </a>
                /
                <strong class="text-primary small">
                    <span id="#">User Groups</span>
                </strong>
            </h3>
            
            <div class="nk-block-des text-soft">
                <p>You have {{groups|length}} user group(s).</p>
            </div>
            <ul class="align-center flex-wrap flex-sm-nowrap gx-4 gy-2">
                {% if current_user|can_create(3) %}
                <li>
                    <a href="{{url_for('settings.new_group')}}" class="btn btn-m btn-primary btn-block">CREATE</a>
                </li>
                {% endif %}
                <li>
                    <a href="#" data-dismiss="modal" class="btn btn-outline-light export" data-toggle="tooltip"
                        data-placement="right" title="Export">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-save" viewBox="0 0 16 16">
                            <path
                                d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v7.293l2.646-2.647a.5.5 0 0 1 .708.708l-3.5 3.5a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L7.5 9.293V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z" />
                        </svg></a>
                    <span class="btn selected-groups"></span>
                </li>
                <li class="li-actions">
                    <div class="drodown">
                        <a href="#" class="dropdown-toggle btn btn-outline-light actions" data-toggle="dropdown">
                            <em class="icon ni ni-setting"></em>
                            <span>Actions</span>
                            <em class="dd-indc icon ni ni-chevron-right"></em>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <ul class="link-list-opt no-bdr">
                                <li><a href="#"><span>Export</span></a></li>
                                {% if current_user|can_delete(2) %}
                                <li><a href="delete-group" class="confirm-delete-group"><span>Delete</span></a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div><!-- .nk-block-head-content -->
        <div class="nk-block-head-content">
            <div class="toggle-wrap nk-block-tools-toggle">
                <a href="#" class="btn btn-icon btn-trigger toggle-expand mr-n1" data-target="pageMenu"><em
                        class="icon ni ni-menu-alt-r"></em></a>
                <div class="toggle-expand-content" data-content="pageMenu">
                    <ul class="nk-block-tools g-3">
                        <li>
                            <div class="drodown">
                                <a href="#" class="dropdown-toggle btn btn-white btn-dim btn-outline-light"
                                    data-toggle="dropdown"><em
                                        class="d-none d-sm-inline icon ni ni-filter-alt"></em><span>Filter
                                        By</span><em class="dd-indc icon ni ni-chevron-right"></em></a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <ul class="link-list-opt no-bdr">
                                        <li><a href="#"><span>Internal Groups</span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div><!-- .toggle-wrap -->
        </div><!-- .nk-block-head-content -->
        {% elif title == "New Group | Olam ERP" %}
        <div class="nk-block-head-content">
            <h3 class="nk-block-title page-title"><a href="{{url_for('settings.manage_groups')}}">
                    Groups
                </a>
                /
                <strong class="text-primary small">
                    <span id="{{slug}}" class="span-new-group">New</span>
                </strong>
            </h3>
            <ul class="align-center flex-wrap flex-sm-nowrap gx-4 gy-2">
                {% if slug %}
                <li>
                    <a href="save" class="btn btn-m btn-primary btn-block save-group">SAVE</a>
                </li>
                {% else %}
                <li>
                    <a href="save" class="btn btn-m btn-primary btn-block save-new-group">SAVE</a>
                </li>
                {% endif %}
                <li>
                    {% if slug %}
                    <a href="{{url_for('settings.discard_group', slug=slug)}}" class="btn btn-outline-light">DISCARD</a>
                    {% else %}
                    <a href="{{url_for('settings.manage_groups')}}" class="btn btn-outline-light">DISCARD</a>
                    {% endif %}
                </li>
            </ul>
        </div>
        <!-- .nk-block-head-content -->
        {% else %}
        <div class="nk-block-head-content">
            <h3 class="nk-block-title page-title"><a href="{{url_for('settings.manage_groups')}}">
                    Groups
                </a>
                /
                <strong class="text-primary small">
                    <span id="{{slug}}"
                        class="span-new-group">{{group.module.bp_name|upper}}&nbsp;-&nbsp;{{group.name}}</span>
                </strong>
            </h3>
            <ul class="align-center flex-wrap flex-sm-nowrap gx-4 gy-2">
                {% if edit %}
                <li>
                    <a href="save-group" class="btn btn-m btn-primary btn-block save-group">SAVE</a>
                </li>
                {% else %}
                {% if current_user|can_write(2) %}
                <li>
                    <a href="{{url_for('settings.edit_group', slug=slug)}}"
                        class="btn btn-m btn-primary btn-block">EDIT</a>
                </li>
                {% endif %}
                {% endif %}
                {% if current_user|can_create(2) %}
                <li>
                    <a href="{{url_for('settings.new_group')}}" class="btn btn-outline-light">CREATE</a>
                </li>
                {% endif %}
            </ul>
        </div>
        {% endif %}
    </div><!-- .nk-block-between -->
</div><!-- .nk-block-head -->

app/templates/settings/settings.html
{% extends "base.html" %}

{% block content %}
<style>
    @media (max-width: 479px) {
        .support-topic-context {
            font-size: 15px !important
        }
    }
</style>
<div class="nk-content-body">
    <div class="nk-content-wrap">
        <div class="nk-block-head">
            <div class="nk-block-between g-3">
                <div class="nk-block-head-content">
                    <h3 class="nk-block-title page-title">
                        <a href="{{url_for('settings.settings')}}">
                            Settings
                        </a>
                    </h3>
                </div>
                <div class="nk-block-head-content">
                    <h3 class="nk-block-title page-title">


                    </h3>
                </div>
                <div class="nk-block-head-content">
                    <a href="{{url_for('main.index')}}"
                        class="btn btn-outline-light bg-white d-none d-sm-inline-flex"><em
                            class="icon ni ni-arrow-left"></em><span>Back</span></a>
                    <a href="{{url_for('main.index')}}"
                        class="btn btn-icon btn-outline-light bg-white d-inline-flex d-sm-none"><em
                            class="icon ni ni-arrow-left"></em></a>
                </div>
            </div>
        </div><!-- .nk-block-head -->
        {% if current_user|can_view_model(1) and current_user|can_view_model(2) %}
        <div class="nk-block">
            <div class="support-topic-item card card-bordered">
                <div class="support-topic-block card-inner">
                    <div class="support-topic-media">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 72 72">
                            <g>
                                <rect x="32" y="16" width="28" height="15" rx="2.5" ry="2.5" style="fill:#6c87fe" />
                                <path
                                    d="M59.7778,61H12.2222A6.4215,6.4215,0,0,1,6,54.3962V17.6038A6.4215,6.4215,0,0,1,12.2222,11H30.6977a4.6714,4.6714,0,0,1,4.1128,2.5644L38,24H59.7778A5.91,5.91,0,0,1,66,30V54.3962A6.4215,6.4215,0,0,1,59.7778,61Z"
                                    style="fill:#8aa3ff" />
                                <path
                                    d="M7.7454,58.9807C9.9352,61.3864,12.4882,61.0163,14,61H59a6.3373,6.3373,0,0,0,5.2562-2.0193Z"
                                    style="fill:#798bff" />
                                <path
                                    d="M29.6309,37.36a3.0236,3.0236,0,0,1-.86-2.39A4.3748,4.3748,0,0,1,32.9961,31h.0078a4.36,4.36,0,0,1,4.22,3.9121,3.0532,3.0532,0,0,1-.8545,2.4482A4.4158,4.4158,0,0,1,33.23,38.53c-.0771,0-.1533-.002-.23-.0049A4.519,4.519,0,0,1,29.6309,37.36Zm13.8359,2.7549a1,1,0,1,0-.9336,1.77c.7207.38,1.4658,2.126,1.4668,4.39V48a1,1,0,0,0,2,0V46.2744C45.999,43.3447,45.0049,40.9268,43.4668,40.1152ZM40.165,37.3965c-.1445.084-.29.168-.4316.2549a1,1,0,0,0,.5215,1.8535.9887.9887,0,0,0,.52-.1465c.1289-.0781.2607-.1543.3916-.23a4.2311,4.2311,0,0,0,2.1465-2.124.9839.9839,0,0,0,.0313-.1045A3.8411,3.8411,0,0,0,40.5,32.5352a1,1,0,0,0-.4922,1.9395,1.8773,1.8773,0,0,1,1.4,1.9092A2.835,2.835,0,0,1,40.165,37.3965ZM36.5,41h-7c-2.5234,0-4.5,2.7822-4.5,6.333V48.5a.8355.8355,0,0,0,.0588.2914.9731.9731,0,0,0,.3508.4946C26.4646,50.2812,29.4614,51,33,51s6.5353-.7187,7.59-1.7139a.9726.9726,0,0,0,.3509-.4949A.8361.8361,0,0,0,41,48.5V47.333C41,43.7822,39.0234,41,36.5,41Z"
                                    style="fill:#4b66bc" />
                            </g>
                        </svg>
                    </div>
                    <div class="support-topic-context">
                        <h5 class="support-topic-title title">Users</h5>
                        {% if current_user|can_view_model(1) %}
                        <div class="support-topic-info"><em class="icon ni ni-chevron-right"></em><a
                                href="{{url_for('settings.manage_users')}}">Manage
                                users.</a></div>
                        {% endif %}
                        {% if current_user|can_view_model(2) %}
                        <div class="support-topic-info"><em class="icon ni ni-chevron-right"></em><a
                                href="{{url_for('settings.manage_groups')}}">Manage
                                groups.</a></div>
                        <br>
                        {% endif %}
                        {% if current_user|can_view_model(1) %}
                        {% if pending_invitations %}
                        <h6 class="support-topic-title title">Pending Invitations</h6>
                        {% for pending_invitation in pending_invitations %}
                        <a
                            href="{{url_for('settings.user', token=pending_invitation.token, slug=pending_invitation.slug)}}"><span
                                class="badge badge-pill badge-outline-primary">{{pending_invitation.partner.email}}</span></a>
                        {% endfor %}
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div><!-- .support-topic-item -->
        </div><!-- .nk-block -->
        {% endif %}
        <div class="nk-block">
            <div class="support-topic-item card card-bordered">
                <div class="support-topic-block card-inner">
                    <div class="support-topic-media">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 90 90">
                            <rect x="5" y="7" width="60" height="56" rx="7" ry="7" fill="#e3e7fe" stroke="#6576ff"
                                stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></rect>
                            <rect x="25" y="27" width="60" height="56" rx="7" ry="7" fill="#e3e7fe" stroke="#6576ff"
                                stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></rect>
                            <rect x="15" y="17" width="60" height="56" rx="7" ry="7" fill="#fff" stroke="#6576ff"
                                stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></rect>
                            <line x1="15" y1="29" x2="75" y2="29" fill="none" stroke="#6576ff" stroke-miterlimit="10"
                                stroke-width="2"></line>
                            <circle cx="53" cy="23" r="2" fill="#c4cefe"></circle>
                            <circle cx="60" cy="23" r="2" fill="#c4cefe"></circle>
                            <circle cx="67" cy="23" r="2" fill="#c4cefe"></circle>
                            <rect x="22" y="39" width="20" height="20" rx="2" ry="2" fill="none" stroke="#6576ff"
                                stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></rect>
                            <circle cx="32" cy="45.81" r="2" fill="none" stroke="#6576ff" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="2"></circle>
                            <path d="M29,54.31a3,3,0,0,1,6,0" fill="none" stroke="#6576ff" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="2"></path>
                            <line x1="49" y1="40" x2="69" y2="40" fill="none" stroke="#6576ff" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="2"></line>
                            <line x1="49" y1="51" x2="69" y2="51" fill="none" stroke="#c4cefe" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="2"></line>
                            <line x1="49" y1="57" x2="59" y2="57" fill="none" stroke="#c4cefe" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="2"></line>
                            <line x1="64" y1="57" x2="66" y2="57" fill="none" stroke="#c4cefe" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="2"></line>
                            <line x1="49" y1="46" x2="59" y2="46" fill="none" stroke="#c4cefe" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="2"></line>
                            <line x1="64" y1="46" x2="66" y2="46" fill="none" stroke="#c4cefe" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="2"></line>
                        </svg>
                    </div>
                    <div class="support-topic-context">
                        <h5 class="support-topic-title title">My Profile</h5>
                        <div class="support-topic-info"><em class="icon ni ni-chevron-right"></em><a
                                href="{{url_for('settings.user_profile')}}">Personal
                                Info</a></div>
                        <div class="support-topic-info"><em class="icon ni ni-chevron-right"></em><a
                                href="#">Notifications</a></div>
                        <div class="support-topic-info"><em class="icon ni ni-chevron-right"></em><a
                                href="#">Security</a></div>
                        <br>

                    </div>
                </div>
            </div><!-- .support-topic-item -->
        </div><!-- .nk-block -->
        <div class="nk-block nk-block-lg">
            <div class="card card-bordered border-primary">
                <div class="card-inner">
                    <div class="nk-cta">
                        <div class="nk-cta-block">
                            <div class="nk-cta-img">
                                <em class="icon icon-circle ni ni-msg"></em>
                            </div>
                            <div class="nk-cta-text">
                                <p>If you experience any difficulties with your settings please contact our support
                                    team.</p>
                            </div>
                        </div>
                        <div class="nk-cta-action">
                            <a href="#" class="btn btn-primary">Contact Us</a>
                        </div>
                    </div>
                </div>
            </div><!-- .card -->
        </div><!-- .nk-block -->
    </div>
    <!-- footer @s -->
    {% include "footer.html" %}
    <!-- footer @e -->
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="modalInvite">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <a href="#" class="close" data-dismiss="modal"><em class="icon ni ni-cross-sm"></em></a>
            <div class="modal-body modal-body-md">
                <h4 id="invite_title" class="title">Invite New User</h4>
                <div style="display: none;" id="dv_notification" class="alert alert-primary" role="alert">
                </div>
                <div class="tab-content">
                    <div class="form-control-wrap">
                        <form id="frm_invite" action="{{url_for('settings.invite')}}" method="POST">
                            {{form.hidden_tag()}}
                            <span id="spn_invite_error" style="color: red;"></span>
                            <div class="input-group">
                                {{form.email(class="form-control", placeholder="Enter e-mail address")}}
                                <div class="input-group-append">
                                    {{form.submit(class="btn btn-primary")}}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <p><b>Remember that each user will increase your monthly fee. Check out pricing on <a
                            href="https://olam-erp.com/pricing">Olam Pricing</a>.</b></p>
            </div>
        </div>
    </div>
</div>
{% include "modals/loading.html" %}
{% endblock %}