app/contacts/forms.py
from app.main.models.partner import Partner
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from flask_babel import _, lazy_gettext as _l
from wtforms.ext.sqlalchemy.fields import QuerySelectField


def get_companies():
    return Partner.query.filter_by(is_company=True)


TITLES = ['Doctor', 'Engineer', 'Madam', 'Ms.', 'Mr.', 'Professor', 'Sir']


class BasicCompanyInfoForm(FlaskForm):
    companyname = StringField(_l('Company Name'))
    phonenumber = StringField(_l('Phone Number'))
    email = StringField(_l('Email Address'))
    website = StringField(_l('Website'))
    postalcode = StringField(_l('Postal/Zip Code'))
    postaladdress = StringField(_l('Postal Address'))
    taxid = StringField(_l('Tax ID'))
    submit1 = SubmitField(_l('Save'))


class BasicIndividualInfoForm(FlaskForm):
    name = StringField(_l('Name'))
    phonenumber = StringField(_l('Phone Number'))
    email = StringField(_l('Email Address'))
    website = StringField(_l('Website'))
    jobposition = StringField(_l('Job Position'))
    postalcode = StringField(_l('Postal/Zip Code'))
    postaladdress = StringField(_l('Postal Address'))
    taxid = StringField(_l('Tax ID'))
    submit2 = SubmitField(_l('Save'))


class AddressInfoForm(FlaskForm):
    postalcode = StringField(_l('Postal/Zip Code'))
    postaladdress = StringField(_l('Postal Address'))
    submit3 = SubmitField(_l('Save'))


class TaxInfoForm(FlaskForm):
    taxid = StringField(_l('Tax ID'))
    submit4 = SubmitField(_l('Save'))

app/contacts/__init__.py
from flask import Blueprint

bp = Blueprint('contacts', __name__)

from app.contacts import routes
    

app/contacts/routes.py
from app.decorators import active_user_required, can_create_access_required, can_write_access_required, model_access_required, module_access_required
from app.main.models.country import City, Country
from app.main.utils import get_countries, get_countries_cities
from flask import url_for, request, jsonify
from app.main.models.module import Module
from flask_login import login_required
from sqlalchemy import log
from app import contacts
from app.contacts import bp
from app.main.models.partner import Partner
from flask import render_template, redirect
from flask_babel import _, get_locale
from app.contacts.forms import BasicCompanyInfoForm, BasicIndividualInfoForm, TITLES, AddressInfoForm, TaxInfoForm
from app import db


@bp.route('/', methods=['GET', 'POST'])
@login_required
@active_user_required
def index():
    contacts = Partner.query.all()
    return render_template('contacts/index.html', title=_('Contacts | Olam ERP'), contacts=contacts)


@bp.route('/new', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(3)
@model_access_required(3)
@can_create_access_required(3)
def create():
    form1 = BasicCompanyInfoForm()
    form2 = BasicIndividualInfoForm()

    titles = TITLES
    countries = Country.query.order_by('name').all()
    companies = Partner.query.filter_by(is_company=True).all()

    if "submit1" in request.form and form1.validate_on_submit():
        partner = Partner(company_name=form1.companyname.data, phone_no=form1.phonenumber.data, website=form1.website.data, is_company=True, is_active=True, email=form1.email.data,
                          country_id=request.form['select_country'], city_id=request.form['select_city'], postal_code=form1.postalcode.data, postal_address=form1.postaladdress.data, tax_id=form1.taxid.data)
        partner.generate_slug()
        db.session.add(partner)
        db.session.commit()
        return redirect(url_for('contacts.view_contact', slug=partner.slug))
    if "submit2" in request.form and form2.validate_on_submit():
        partner = Partner(name=form2.name.data,
                          phone_no=form2.phonenumber.data, title=request.form['select_title'], parent_id=request.form['select_company'], website=form2.website.data, is_individual=True, is_active=True, function=form2.jobposition.data, email=form2.email.data)
        partner.generate_slug()
        db.session.add(partner)
        db.session.commit()
        return redirect(url_for('contacts.view_contact', slug=partner.slug))
    return render_template('contacts/create.html', title=_('New Contact | Olam ERP'), form1=form1, form2=form2, companies=companies, titles=titles, countries=countries)


@bp.route('/view_contact/<slug>', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(3)
@model_access_required(3)
def view_contact(slug):
    form1 = BasicCompanyInfoForm()
    form2 = BasicIndividualInfoForm()
    form3 = AddressInfoForm()
    form4 = TaxInfoForm()
    partner = Partner.query.filter_by(slug=slug).first()
    titles = TITLES
    companies = Partner.query.filter_by(is_company=True).all()
    partners = Partner.query.all()
    countries = Country.query.order_by('name').all()

    for idx, _partner in enumerate(partners):
        if _partner.id == partner.id:
            current_index = idx
            prev_index = current_index - 1
            next_index = current_index + 1
        

    if "submit1" in request.form and form1.validate_on_submit():
        if partner.is_company:
            partner.company_name = form1.companyname.data
            partner.phone_no = form1.phonenumber.data
            partner.website = form1.website.data
            partner.email = form1.email.data
            db.session.commit()
            return redirect(url_for('contacts.view_contact', slug=partner.slug))
    if "submit2" in request.form and form2.validate_on_submit():
        if partner.is_individual or partner.is_tenant:
            partner.name = form2.name.data
            partner.title = request.form['select_title']
            partner.function = form2.jobposition.data
            partner.phone_no = form2.phonenumber.data
            partner.email = form2.email.data
            partner.website = form2.website.data
            db.session.commit()
            return redirect(url_for('contacts.view_contact', slug=partner.slug))
    if "submit3" in request.form and form3.validate_on_submit():
        partner.country_id = request.form['select_country']
        partner.city_id = request.form['select_city'] if request.form['select_city'].isdigit(
        ) else None
        partner.postal_code = form3.postalcode.data
        partner.postal_address = form3.postaladdress.data
        db.session.commit()
        return redirect(url_for('contacts.view_contact', slug=partner.slug))
    if "submit4" in request.form and form4.validate_on_submit():
        partner.tax_id = form4.taxid.data
        db.session.commit()
        return redirect(url_for('contacts.view_contact', slug=partner.slug))
    return render_template('contacts/view.html', title=_('Contact Details | Olam ERP'), partner=partner, form1=form1, form2=form2, form3=form3, form4=form4, titles=titles, companies=companies, countries=countries, current_index=current_index+1, prev_index=prev_index, next_index=next_index, partners=partners)


@bp.route('/get_cities', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(3)
@model_access_required(3)
def get_city():
    if request.method == "POST":
        cities = City.to_collection_dict(
            City.query.filter_by(country_id=request.json['country']).order_by('name'))
        return jsonify({'cities': cities})


@bp.route('/address/<slug>', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(3)
@model_access_required(3)
def addresses(slug):
    partner = Partner.query.filter_by(slug=slug).first()
    children = Partner.query.filter_by(parent_id=partner.id).all()
    return render_template('contacts/addresses.html', title=_(partner.company_name + ' | Olam ERP'), partner=partner, children=children)


@bp.route('/meetings/<slug>', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(3)
@model_access_required(3)
def meetings(slug):
    partner = Partner.query.filter_by(slug=slug).first()
    return render_template('contacts/meetings.html', title=_('Meetings | Olam ERP'), partner=partner)


@bp.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
@active_user_required
@module_access_required(3)
@model_access_required(3)
@can_write_access_required(3)
def edit():
    pass

app/templates/contacts/addresses.html
{% extends "base.html" %}

{% block content %}
<div class="nk-content-body">
    <div class="nk-content-wrap">
        {% include "contacts/contacts_blockhead.html" %}
        <div class="nk-block">
            <div class="card card-bordered">
                {% include "contacts/contacts_tab.html" %}

                <div class="card-inner">
                    <table class="datatable-init nk-tb-list nk-tb-ulist" data-auto-responsive="false">
                        <thead>
                            <tr class="nk-tb-item nk-tb-head">
                                <th class="nk-tb-col nk-tb-col-check">
                                    <div class="custom-control custom-control-sm custom-checkbox notext">
                                        <input type="checkbox" class="custom-control-input" id="uid">
                                        <label class="custom-control-label" for="uid"></label>
                                    </div>
                                </th>
                                <th class="nk-tb-col"><span class="sub-text">Name</span></th>
                                <th class="nk-tb-col tb-col-md"><span class="sub-text">Job Position</span>
                                </th>
                                <th class="nk-tb-col tb-col-xl"><span class="sub-text">Email</span></th>
                                <th class="nk-tb-col tb-col-xl"><span class="sub-text">Phone</span></th>
                                <th class="nk-tb-col tb-col-xl"><span class="sub-text">Contact Person</span></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for child in children %}
                            <tr class="nk-tb-item">
                                <td class="nk-tb-col nk-tb-col-check">
                                    <div class="custom-control custom-control-sm custom-checkbox notext">
                                        <input type="checkbox" class="custom-control-input" id="{{child.id}}">
                                        <label class="custom-control-label" for="{{child.id}}"></label>
                                    </div>
                                </td>
                                <td class="nk-tb-col">{{child.name}}</td>
                                <td class="nk-tb-col tb-col-md">{{child.function}}</td>
                                <td class="nk-tb-col tb-col-md">{{child.email}}</td>
                                <td class="nk-tb-col tb-col-md">{{child.phone_no}}</td>
                                <td class="nk-tb-col nk-tb-col-check">
                                    <div class="custom-control custom-control-sm custom-checkbox notext">
                                        <input type="checkbox" class="custom-control-input" {% if child.contact_person %}checked{% endif %}>
                                        <label class="custom-control-label"></label>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div><!-- .nk-block-head -->

            </div><!-- .card -->
        </div><!-- .nk-block -->
    </div>
    <!-- footer @s -->
    {% include "footer.html" %}
    <!-- footer @e -->
</div>
{% endblock %}

app/templates/contacts/contacts_blockhead.html
<div class="nk-block-head">
    <div class="nk-block-between g-3">
        <div class="nk-block-head-content">
            <h3 class="nk-block-title page-title">
                <a href="{{url_for('contacts.index')}}">
                    Contacts
                </a>
                /
                <strong class="text-primary small">
                    {% if partner.is_company %}
                    {{partner.company_name|title}}
                    {% elif partner.is_tenant %}
                    {{partner.name|title}}
                    {% elif partner.is_individual %}
                    {{partner.name|title}}, {{partner.parent.company_name}}
                    {% endif %}
                </strong>
            </h3>
            <ul class="align-center flex-wrap flex-sm-nowrap gx-4 gy-2">
                {% if current_user|can_write(3) %}
                <li>
                    <a href="{{url_for('contacts.edit', slug=partner.slug)}}" class="btn btn-primary">
                        EDIT
                    </a>
                </li>
                {% endif %}
                {% if current_user|can_create(3) %}
                <li>
                    <a href="{{url_for('contacts.create')}}" class="btn btn-outline-light">
                        CREATE
                    </a>
                </li>
                {% endif %}
                <li class="li-actions">
                    <div class="drodown">
                        <a href="#" class="dropdown-toggle btn btn-outline-light actions" data-toggle="dropdown">
                            <em class="icon ni ni-setting"></em>
                            <span>Actions</span>
                            <em class="dd-indc icon ni ni-chevron-right"></em>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <ul class="link-list-opt no-bdr">
                                {% if current_user|can_write(3) %}
                                <li><a href="#"><span>Archive</span></a></li>
                                {% endif %}
                                {% if current_user|can_create(3) %}
                                <li><a href="#"><span>Duplicate</span></a></li>
                                {% endif %}
                                {% if current_user|can_delete(3) %}
                                <li><a href="#"><span>Delete</span></a></li>
                                {% endif %}
                                {% if current_user|can_write(3) %}
                                <li><a href="#"><span>Grant Portal Access</span></a></li>
                                <li><a href="#"><span>Send SMS Text Message</span></a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="nk-block-head-content">
            <div class="toggle-wrap nk-block-tools-toggle">
                <a href="#" class="btn btn-icon btn-trigger toggle-expand mr-n1" data-target="pageMenu"><em
                        class="icon ni ni-menu-alt-r"></em></a>
                <div class="toggle-expand-content" data-content="pageMenu">
                    <ul class="nk-block-tools g-3">
                        {% if title == 'Contact Details | Olam ERP' %}
                        <li style="margin-left: auto !important;">
                            <span>{{current_index}}</span>/<span>{{partners|length}}</span>
                        </li>
                        {% if current_index != 1 %}
                        <li>
                            {% if edit %}
                            <a href="{{url_for('contacts.edit', slug=partners[prev_index].slug)}}"
                                class="btn btn-icon btn-m btn-primary d-none d-sm-inline-flex"><em
                                    class="icon ni ni-caret-left"></em></a>
                            <a href="{{url_for('contacts.edit', slug=partners[prev_index].slug)}}"
                                class="btn btn-icon btn-m btn-primary d-inline-flex d-sm-none"><em
                                    class="icon ni ni-caret-left"></em></a>
                            {% else %}
                            <a href="{{url_for('contacts.view_contact', slug=partners[prev_index].slug)}}"
                                class="btn btn-icon btn-m btn-primary d-none d-sm-inline-flex"><em
                                    class="icon ni ni-caret-left"></em></a>
                            <a href="{{url_for('contacts.view_contact', slug=partners[prev_index].slug)}}"
                                class="btn btn-icon btn-m btn-primary d-inline-flex d-sm-none"><em
                                    class="icon ni ni-caret-left"></em></a>
                            {% endif %}
                        </li>
                        {% endif %}
                        {% if next_index != partners|length %}
                        <li>
                            {% if edit %}
                            <a href="{{url_for('contacts.edit', slug=partners[next_index].slug)}}"
                                class="btn btn-icon btn-m btn-primary d-none d-sm-inline-flex"><em
                                    class="icon ni ni-caret-right"></em></em></a>
                            <a href="{{url_for('contacts.edit', slug=partners[next_index].slug)}}"
                                class="btn btn-icon btn-m btn-primary d-inline-flex d-sm-none"><em
                                    class="icon ni ni-caret-right"></em></a>
                            {% else %}
                            <a href="{{url_for('contacts.view_contact', slug=partners[next_index].slug)}}"
                                class="btn btn-icon btn-m btn-primary d-none d-sm-inline-flex"><em
                                    class="icon ni ni-caret-right"></em></em></a>
                            <a href="{{url_for('contacts.view_contact', slug=partners[next_index].slug)}}"
                                class="btn btn-icon btn-m btn-primary d-inline-flex d-sm-none"><em
                                    class="icon ni ni-caret-right"></em></a>
                            {% endif %}
                        </li>
                        {% endif %}
                        {% endif %}
                    </ul>
                </div>
            </div><!-- .toggle-wrap -->
        </div>
    </div>
</div><!-- .nk-block-head -->

app/templates/contacts/contacts_tab.html
<ul class="nav nav-tabs nav-tabs-mb-icon nav-tabs-card">
        <li class="nav-item">
                {% if partner.is_company %}
                <a class="nav-link" href="{{url_for('contacts.view_contact', slug=partner.slug)}}"><em
                                class="icon ni ni-linux-server"></em></em><span>Company</span></a>
                {% elif partner.is_tenant or partner.is_individual %}
                <a class="nav-link" href="{{url_for('contacts.view_contact', slug=partner.slug)}}"><em
                                class="icon ni ni-user-fill-c"></em><span>Personal</span></a>
                {% endif %}
        </li>
        <li class="nav-item">
                {% if partner.is_company %}
                <a class="nav-link" href="{{url_for('contacts.addresses', slug=partner.slug)}}"><em
                                class="icon ni ni-users-fill"></em><span>Contacts & Addresses</span></a>
                {% elif partner.is_tenant or partner.is_individual %}
                <a class="nav-link" href="{{url_for('contacts.meetings', slug=partner.slug)}}"><em
                                class="icon ni ni-calendar-booking"></em><span>Meetings</span></a>
                {% endif %}
        </li>
        <li class="nav-item">
                {% if partner.is_company %}
                <a class="nav-link" href="{{url_for('contacts.meetings', slug=partner.slug)}}"><em
                                class="icon ni ni-calendar-booking"></em><span>Meetings</span></a>
                {% endif %}
                {% if partner.is_individual and not partner.is_tenant %}
                <a class="nav-link" href="#">
                        <em class="icon ni ni-star-fill"></em>
                        <span>Opportunities</span>
                </a>
                {% endif %}
        </li>
        <li class="nav-item">
                {% if partner.is_company %}
                <a class="nav-link" href="#">
                        <em class="icon ni ni-sign-dollar"></em>
                        <span>Sales</span>
                </a>
                {% endif %}
                {% if partner.is_individual and not partner.is_tenant %}
                <a class="nav-link" href="#">
                        <em class="icon ni ni-sign-dollar"></em>
                        <span>Sales</span>
                </a>
                {% endif %}
        </li>
        <li class="nav-item">
                {% if partner.is_company %}
                <a class="nav-link" href="#">
                        <em class="icon ni ni-edit"></em>
                        <span>Invoiced</span>
                </a>
                {% endif %}
                {% if partner.is_individual and not partner.is_tenant %}
                <a class="nav-link" href="#">
                        <em class="icon ni ni-edit"></em>
                        <span>Invoiced</span>
                </a>
                {% endif %}
        </li>
</ul><!-- .nav-tabs -->

app/templates/contacts/index.html
{% extends "base.html" %}

{% block content %}
<div class="nk-content-body">
    <div class="nk-content-wrap">
        <div class="nk-block-head nk-block-head-sm">
            <div class="nk-block-between">
                <div class="nk-block-head-content">
                    <h3 class="nk-block-title page-title">Contacts</h3>
                    <div class="nk-block-des text-soft">
                        <p>You have {{contacts|length}} contacts.</p>
                    </div>
                </div><!-- .nk-block-head-content -->
                <div class="nk-block-head-content">
                    <div class="toggle-wrap nk-block-tools-toggle">
                        <a href="#" class="btn btn-icon btn-trigger toggle-expand mr-n1" data-target="pageMenu"><em
                                class="icon ni ni-menu-alt-r"></em></a>
                        <div class="toggle-expand-content" data-content="pageMenu">
                            <ul class="nk-block-tools g-3">
                                <li>
                                    <div class="drodown">
                                        <a href="#" class="dropdown-toggle btn btn-white btn-dim btn-outline-light"
                                            data-toggle="dropdown"><em
                                                class="d-none d-sm-inline icon ni ni-filter-alt"></em><span>Filter
                                                By</span><em class="dd-indc icon ni ni-chevron-right"></em></a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <ul class="link-list-opt no-bdr">
                                                <li><a href="#"><span>Individuals</span></a></li>
                                                <li><a href="#"><span>Companies</span></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </li>
                                {% if current_user|can_create(3) %}
                                <li class="nk-block-tools-opt"><a href="{{url_for('contacts.create')}}"
                                        class="btn btn-primary"><em class="icon ni ni-plus"></em><span>Create</span></a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div><!-- .toggle-wrap -->
                </div><!-- .nk-block-head-content -->
            </div><!-- .nk-block-between -->
            <div class="nk-search-box">
                <div class="form-group">
                    <div class="form-control-wrap">
                        <input id="search_contacts" type="text" class="form-control form-control-lg"
                            placeholder="Search...">
                        <button class="form-icon form-icon-right">
                            <em class="icon ni ni-search"></em>
                        </button>
                    </div>
                </div>
            </div>
        </div><!-- .nk-block-head -->
        <div class="nk-block">
            <div class="row g-gs">
                {% for contact in contacts %}
                <div class="col-sm-6 col-xl-3">
                    <div class="card card-bordered">
                        <div class="card-inner">
                            <div class="team">
                                <div class="team-options">
                                    <div class="drodown">
                                        <a href="#" class="dropdown-toggle btn btn-sm btn-icon btn-trigger"
                                            data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <ul class="link-list-opt no-bdr">
                                                <li><a href="#"><em class="icon ni ni-eye"></em><span>View
                                                            Details</span></a></li>
                                                <li><a href="#"><em class="icon ni ni-mail"></em><span>Send
                                                            Email</span></a></li>
                                                <li class="divider"></li>
                                                <li><a href="#"><em class="icon ni ni-shield-star"></em><span>Reset
                                                            Pass</span></a></li>
                                                <li><a href="#"><em class="icon ni ni-shield-off"></em><span>Reset
                                                            2FA</span></a></li>
                                                <li><a href="#"><em class="icon ni ni-na"></em><span>Suspend
                                                            User</span></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="user-card user-card-s2">
                                    <div class="user-info">
                                        <h6>
                                            {% if contact.is_tenant or contact.is_individual %}
                                            {{contact.name}}
                                            {% elif contact.is_company %}
                                            {{contact.company_name}}
                                            {% endif %}
                                        </h6>
                                        <h6>
                                            {% if contact.is_tenant %}
                                            {{contact.company.name|title}}
                                            {% elif contact.is_individual %}
                                            {{contact.parent.company_name|title}}
                                            {% endif %}
                                        </h6>
                                        <span class="sub-text">
                                            {% if (contact.is_tenant or contact.is_individual) and (contact.function) %}
                                            {{contact.function}}
                                            {% elif contact.is_company %}
                                            {{contact.city.name}},&nbsp;{{contact.country.name}}
                                            {% endif %}
                                        </span>
                                        <span class="sub-text">
                                            {{contact.email}}
                                        </span>
                                    </div>
                                </div>
                                <div class="team-view">
                                    <a href="{{url_for('contacts.view_contact', slug=contact.slug)}}"
                                        class="btn btn-round btn-outline-light w-150px"><span>View Profile</span></a>
                                </div>
                            </div><!-- .team -->
                        </div><!-- .card-inner -->
                    </div><!-- .card -->
                </div><!-- .col -->
                {% endfor %}
            </div>
        </div><!-- .nk-block -->

    </div>
    <!-- footer @s -->
    {% include "footer.html" %}
    <!-- footer @e -->
</div>
{% endblock %}